//TA THS GLWSSAS
#define PROGRAM 1
#define FUNCTION 2
#define ENDFUNCTION 3
#define VARS 4
#define INTEGER 5
#define CHAR 6
#define START_MAIN 7
#define ENDMAIN 8
#define WHILE 9
#define ENDWHILE 10
#define FOR 11
#define ENDFOR 12
#define IF 13
#define THEN 14
#define ELSEIF 15
#define ELSE 16
#define ENDIF 17
#define SWITCH 18
#define CASE 19
#define DEFAULT 20
#define ENDSWITCH 21
#define BREAK 22
#define TO 23
#define STEP 24
#define RETURN 25

//TA DIKA MAS
#define M_NAME 26
#define KEIMENO 27
